name: Components request
description: Suggest an idea for a new component
title: Description of the component request
labels: enhancement

body:
  - type: textarea
    attributes:
      label: Why would you like to add a new component?
      placeholder: >-
      	A clear and concise description of why the component should be added.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Name the native widgets.
      placeholder: >-
        A list of the native widgets of Gtk/Libadwaita or AppKit, if you know them.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe your idea for the implementation.
      placeholder: >-
        What could the implementation be like in Dvandva?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      placeholder: >-
        Add any other context about the component request here.
    validations:
      required: false
